# Generated by Django 6.0.5 on 2026-05-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('heading1', models.CharField(default='', max_length=100)),
                ('contant1', models.CharField(default='', max_length=5000)),
                ('heading2', models.CharField(default='', max_length=50)),
                ('contant2', models.CharField(default='', max_length=5000)),
                ('heading3', models.CharField(default='', max_length=100)),
                ('contant3', models.CharField(default='', max_length=5000)),
                ('publish_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='blog_image')),
            ],
        ),
    ]
