# Generated by Django 6.0.5 on 2026-05-15 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must contain only numbers and be between 11 to 13 digits.', regex='^\\d{11,13}$')]),
        ),
    ]
