# Generated by Django 6.0.5 on 2026-05-17 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(4, message='Description must be at least 4 characters long.')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4, message='Email must be at least 4 characters long.')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(4, message='Name must be at least 4 characters long.')]),
        ),
    ]
