# Generated by Django 6.0.5 on 2026-05-17 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_contact_desc_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=255)),
                ('paragraph1', models.CharField(max_length=500)),
                ('image', models.ImageField(default='', upload_to='static/image')),
                ('heading2', models.CharField(max_length=255)),
                ('paragraph2', models.CharField(max_length=500)),
                ('paragraph3', models.CharField(max_length=500)),
                ('paragraph4', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3, message='Name must be at least 3 characters long.')]),
        ),
    ]
