# Generated by Django 6.0.5 on 2026-05-17 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_about_alter_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
