# Generated by Django 6.0.5 on 2026-05-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_about_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(default='', upload_to='home_image/'),
        ),
    ]
